# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Продукт',
                'db_table': 'products',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
            options={
                'verbose_name': 'Изображение',
                'db_table': 'product_image',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
