# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productimage_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
