# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(default='', max_length=100, verbose_name='Номер заказа')),
                ('user_phone', models.CharField(default='', max_length=100, verbose_name='Телефон')),
                ('user_email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='core.Product')),
            ],
        ),
    ]
