# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160324_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='left_in_stock',
        ),
    ]
