# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160324_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='left_in_stock',
            field=models.IntegerField(default=1, verbose_name='Осталось на складе'),
        ),
    ]
