# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160326_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.PositiveIntegerField(default=1, verbose_name='Отображение продукта'),
        ),
    ]
